<?php 
$mysql_host = "localhost"; //Mysql host...
$mysql_user = "root"; //Mysql user...
$mysql_password = "anike"; //Mysql password
$mysql_database = "colegio"; //Mysql database...
$mysql_tableprefix = "syrup"; //Table prefix...

?>